In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")

In [3]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


#### Survival rate by Sex

In [4]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

#### Average Age by Pclass

In [5]:
df.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

#### Count by Embarked

In [13]:
df.groupby("Embarked")["PassengerId"].count()

Embarked
C    168
Q     77
S    644
Name: PassengerId, dtype: int64

### Joining Two dataframe (merge & Join)

In [16]:
df1 = pd.read_csv("LOTR.csv")
df2 = pd.read_csv("LOTR 2.csv")

In [17]:
df1.merge(df2, how = "inner")

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [18]:
df1.merge(df2, how ="left")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [20]:
df1.set_index("FellowshipID").join(df2.set_index("FellowshipID"), lsuffix = "_left", rsuffix = "_right", how = "outer")

             FirstName_left     Skills FirstName_right     Age
FellowshipID
1001                  Frodo     Hiding           Frodo    50.0
1002                Samwise  Gardening         Samwise    39.0
1003                Gandalf     Spells             NaN     NaN
1004                 Pippin  Fireworks             NaN     NaN
1006                    NaN        NaN         Legolas  2931.0
1007                    NaN        NaN          Elrond  6520.0
1008                    NaN        NaN        Barromir    51.0

### aggregations

In [24]:
df.groupby("Sex").agg({
    "Survived": "mean",
    "Pclass": "mean",
    "Embarked": "count"
})

        Survived    Pclass  Embarked
Sex
female  0.742038  2.159236       312
male    0.188908  2.389948       577

In [25]:
df.groupby("Embarked").agg({
    "Age": "mean",
    "Fare": "mean"
})

                Age       Fare
Embarked
C         30.814769  59.954144
Q         28.089286  13.276030
S         29.445397  27.079812